apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-cicd

bases:
  - ../../base

images:
- name: changeme
  newName: quay-quay-enterprise-registry.apps.simpsons.lab.gfontana.me/demo/quarkus-quickstarts
  newTag: "v1"