apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: quarkus-build-and-deploy-pr
  namespace: demo-cicd
spec:
  params:
    - name: APP_NAME
      value: quarkus-quickstarts
    - name: GIT_REPO
      value: 'https://github.com/giofontana/demo-cicd.git'
    - name: GIT_REVISION
      value: ''
    - name: IMAGE_NAME
      value: >-
        quay-quay-enterprise-registry.apps.simpsons.lab.gfontana.me/demo/quarkus-quickstarts:v1
    - name: PATH_CONTEXT
      value: quarkus-getting-started
    - name: VERSION
      value: openjdk-17-ubi8
  pipelineRef:
    name: quarkus-build-and-deploy
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi